# Write a python program to calculate the force generated by a body moving at certain acceleration. 
# Your program should get the mass and acceleration from the user with correct units.. 
# Display the force with the correct unit.
# Author : Sonam Wangchu
# Date : April 20 2021


# Get the mass and acceleration of a body from the user.

mass = float(input("What is the mass of the body in Kg? :"))
acceleration = float(input("What is the acceleration at which the body is travelling? :"))

# Calculate the force, f = ma
force = mass * acceleration

# print out the value of force to the user
print(f"The body of mass {mass} moving at {acceleration}m/s genrarates a force of {force}N")
